# Generated by Django 6.0.3 on 2026-04-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_google", "0003_taskexecution_max_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("definition", models.TextField()),
                ("project_id", models.TextField()),
                ("location", models.TextField(default="us-central1")),
                ("service_account", models.TextField(blank=True, default="")),
                (
                    "cloud_workflow_resource_name",
                    models.TextField(null=True, unique=True),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow Definition",
                "verbose_name_plural": "Workflow Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="callback_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="callback_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
