# Generated by Django 6.0.3 on 2026-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_google", "0004_workflow_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="callback_url",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
